In [2]:
# Check how the padding affects the model at different stages
%load_ext autoreload
%autoreload 2
from fcn import FCN32s
import torch
import numpy as np

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = FCN32s(10).to(device)

for i in range(10):
  # create fake data to feed in
  inp = torch.rand(12,3,512,512).to(device)
  lbl = torch.rand(12,512,512).to(device)
  out = model(inp)

torch.save({"model_state": model.state_dict()}, "p2.pkl")
print(out.shape)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([12, 10, 512, 512])


In [ ]:
## Check that the pretrained weight loading works
%load_ext autoreload
%autoreload 2
from fcn import FCN32s
import torch
import numpy as np
import torchvision.models as models

model_raw = FCN32s(10, pretrained=False)
#print(model_raw.conv_block_1[0].weight[0,:,:,:])

model_pre = FCN32s(10)
print(model_pre.conv_block_1[0].weight[0,:,:,:])


vgg16 = models.vgg16(pretrained=True)
print(list(vgg16.features.children())[0].weight[0,:,:,:])

print(model_pre.classifier[0].weight)
print(vgg16.classifier[0].weight)

In [1]:
%load_ext autoreload
%autoreload 2
from autoencoder import SmallAutoEncoder
import torch
import numpy as np

model = SmallAutoEncoder(10)

img = torch.rand(1, 1, 28, 28)

out = model(img)

print(out.shape)


TypeError: __init__() takes 1 positional argument but 2 were given

In [6]:
%load_ext autoreload
%autoreload 2
from gan import ACDiscriminatorNet, ACGeneratorNet
import torch
import numpy as np

disc = ACDiscriminatorNet()
gen = ACGeneratorNet(100)

noise = torch.rand(1, 100)
lbl = torch.randint(10, (1,))
print(f"lbl {lbl}")
#out = gen(noise, lbl)

out_1, out_2 = disc(torch.rand(1, 784))
print(out_1)
print(out_2)

lbl1 = torch.randint(10, (10,1))
print(f"lbl {lbl}")
lbl2 = torch.randint(10, (10,1))
f = [(l1.item(), l2.item()) for l1, l2 in zip(lbl1, lbl2)]

print(f)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
lbl tensor([2])
tensor([[0.0193]], grad_fn=<AddmmBackward>)
tensor([[ 0.0288,  0.0703, -0.0173,  0.0009,  0.0971,  0.0394,  0.0179, -0.0180,
         -0.0117,  0.0198]], grad_fn=<AddmmBackward>)
lbl tensor([2])
[(1, 5), (2, 6), (3, 7), (1, 2), (8, 6), (1, 7), (9, 3), (6, 4), (3, 8), (9, 4)]


In [19]:
%load_ext autoreload
%autoreload 2
from gan import DCGeneratorNet, DCDiscriminatorNet
import torch
import numpy as np

gen = DCGeneratorNet(100)
disc = DCDiscriminatorNet()

noise = torch.rand(12, 100, 1, 1)
print(noise.shape)

o = gen(noise)
print(f'gen {o.shape}')
o = disc(o)
print(f'disc {o.shape}')
o = o.view(-1)
print(f'disc {o.shape}')
print(o)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
torch.Size([12, 100, 1, 1])
gen torch.Size([12, 3, 64, 64])
disc torch.Size([12, 1, 1, 1])
disc torch.Size([12])
tensor([0.4972, 0.4970, 0.4969, 0.4999, 0.4962, 0.4976, 0.4982, 0.4973, 0.4986,
        0.4974, 0.4963, 0.4988], grad_fn=<ViewBackward>)
