In [16]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [8]:
from data_loader.mit_scene_parsing import MITSceneParsingLoader
import data_loader
import models

k = MITSceneParsingLoader()
print(f"k num cls: {k.n_classes}")
k = data_loader.get_loader("mit_sceneparsing_benchmark")()

print(k.files[15828])
#img = Image.open(k.files[15828])
#img.show()
img, annt = k[15828]
#print(img.shape)
#print(annt.shape)


from PIL import Image
#Image.fromarray(img, 'RGB').show()
#print(img.shape)
#Image.fromarray(annt).show()

import torch

tr = torch.rand((2,3,4))
print(tr.size())
torch.cuda.device_count()

model = models.get_model("fcn32s", 21)
print(model.conv_block_1)

print(torch.cuda.device_count())

import numpy as np
img = np.array([[34,6], [6,4]])
print(img.shape)

print("----")
tnsr = torch.from_numpy(img).long()

print(tnsr.data)
print(tnsr)


Found 20209 training images
k num cls: 151
Found 20209 training images
data_loader/data/ADEChallengeData2016/images/training/ADE_train_00013508.jpg
torch.Size([2, 3, 4])
Sequential(
  (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(100, 100))
  (1): ReLU(inplace=True)
  (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
  (3): ReLU(inplace=True)
  (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=True)
)
1
(2, 2)
----
tensor([[34,  6],
        [ 6,  4]])
tensor([[34,  6],
        [ 6,  4]])


In [13]:
# Test model size
from utils.pytorch_modelsize import SizeEstimator
import models

model = models.get_model("fcn32s", 151)
import torch
import torch.nn as nn
from torch.autograd import Variable
import numpy as np

class Model(nn.Module):

    def __init__(self):
        super(Model,self).__init__()

        self.conv0 = nn.Conv2d(1, 16, kernel_size=3, padding=5)
        self.conv1 = nn.Conv2d(16, 32, kernel_size=3)

    def forward(self, x):
        h = self.conv0(x)
        h = self.conv1(h)
        return h

model = Model()
se = SizeEstimator(model, input_size=(8,3,512,512))
print(se.estimate_size())

RuntimeError: Given groups=1, weight of size [16, 1, 3, 3], expected input[8, 3, 512, 512] to have 1 channels, but got 3 channels instead

In [12]:
path = "data_loader/data/ADEChallengeData2016/images/testing/ADE_val_00000004.jpg"

import os

os.path.splitext(os.path.basename(path))[0]

import torch

tnsr_0 = torch.load("results/tnsr_0.pkl")
print(tnsr_0['out'])

tnsr_1 = torch.load("results/tnsr_1.pkl")
print(tnsr_1['out'])

tnsr_2 = torch.load("results/tnsr_2.pkl")
print(tnsr_2['out'])

tensor([[[[  0.5898,   0.5898,   0.5898,  ...,   0.6964,   0.6964,   0.6964],
          [  0.5898,   0.5898,   0.5898,  ...,   0.6964,   0.6964,   0.6964],
          [  0.5898,   0.5898,   0.5898,  ...,   0.6964,   0.6964,   0.6964],
          ...,
          [  0.5836,   0.5836,   0.5836,  ...,   0.6164,   0.6164,   0.6164],
          [  0.5836,   0.5836,   0.5836,  ...,   0.6164,   0.6164,   0.6164],
          [  0.5836,   0.5836,   0.5836,  ...,   0.6164,   0.6164,   0.6164]],

         [[  1.6740,   1.6740,   1.6740,  ...,   1.7139,   1.7139,   1.7139],
          [  1.6740,   1.6740,   1.6740,  ...,   1.7139,   1.7139,   1.7139],
          [  1.6740,   1.6740,   1.6740,  ...,   1.7139,   1.7139,   1.7139],
          ...,
          [ -0.0848,  -0.0848,  -0.0848,  ...,  -0.0317,  -0.0317,  -0.0317],
          [ -0.0848,  -0.0848,  -0.0848,  ...,  -0.0317,  -0.0317,  -0.0317],
          [ -0.0848,  -0.0848,  -0.0848,  ...,  -0.0317,  -0.0317,  -0.0317]],

         [[  0.8090,   0.8090,